name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./compute
    
    steps:
    - uses: actions/checkout@v2
    - name: create bin
      run: mkdir bin
    - name: make
      run: make
