# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./frontend/server

    steps:
    - uses: actions/checkout@v2
      with:
        working-directory: ./frontend/server
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        working-directory: ./frontend/server
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build
  


  build-ui:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./frontend/ui

    steps:
    - uses: actions/checkout@v2
      with:
        working-directory: ./frontend/ui
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        working-directory: ./frontend/ui
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build
